<h1 align="center">NumPy Assignment</h1>

<p align="center">
<b>Submitted by:</b> Chippada Hemalatha<br>
<b>Batch:</b> 3
</p>


Section A – Conceptual Understanding

A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasons. 

**Answer**



NumPy arrays are preferred because they make working with numerical data easier and faster.

**Reasons:**

1. **Faster computation** – NumPy performs numerical operations faster than normal Python lists.

2. **Memory efficient** – NumPy arrays use memory efficiently for storing numerical data.

3. **Vectorized operations** – We can perform calculations on many values at the same time without using `for` loops.

4. **Mathematical functions** – NumPy provides many built-in functions useful for numerical calculations in AI/ML.


A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets? 

**Answer**

**Vectorization** means performing an operation on the whole NumPy array instead of using a Python `for` loop for each value.

**Why it matters with large datasets:**

1. **Faster execution** – NumPy can perform array operations faster than normal Python loops.
2. **Less loop overhead** – It avoids repeating Python-level loop operations for every value.
3. **Useful for large datasets** – When there are many values, vectorization can save execution time.
4. **Simple code** – We can perform calculations on the entire array using a single NumPy operation.

A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each. 

**Answer**

For two compatible 2D arrays **A** and **B**:

1. **`A * B` – Element-wise multiplication**
   - It multiplies the values at the same positions in both arrays.
   - In a neural network, it can be used when we want to scale or multiply values element by element.

2. **`A @ B` – Matrix multiplication**
   - It performs matrix multiplication between A and B.
   - In a neural network, it is commonly used to multiply input data with weight matrices.
   
**Neural-network situations:**

- `A * B`: Used when we want to multiply or scale values element by element.
- `A @ B`: Used when multiplying input data with a weight matrix in a neural network.

A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise. 

**Answer**

Broadcasting is a NumPy feature that allows arrays with different shapes to work together in element-wise operations when their dimensions are compatible.

**General rule:**

1. NumPy compares the shapes from the **last dimension**.
2. The dimensions should be **the same** or **one of them should be 1**.
3. If these conditions are satisfied, NumPy can automatically adjust the smaller array and perform the operation.
4. If the shapes are not compatible, NumPy gives a shape error.

A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?     

**Answer**


 `flatten()` vs `ravel()`

- **`flatten()`**: Converts the array into a 1D array and creates a new copy of the data.
- **`ravel()`**: Converts the array into a 1D array and can use the original array's memory instead of creating a new copy.

### Preferred Choice: `ravel()`

For a memory-constrained application working with large images, I would prefer **`ravel()`** when possible.

**Why:** `flatten()` creates a separate copy, which needs extra memory. `ravel()` can avoid this extra memory by using a view of the original array.

A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example. 

**Answer**


For a 2D NumPy array, 

`axis=0` means the operation is performed down the rows, so we get a result for each column.

`axis=1` means the operation is performed across the columns, so we get a result for each row.


**Example:**


In [7]:
import numpy as np
a = np.array([[6, 5, 4],
              [3, 2, 1]])

print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[9 7 5]
[15  6]


A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization. 

**Answer**

Normalization or standardization is important because different numerical features may have different ranges of values. Bringing the features to a similar scale helps most ML models learn properly and prevents features with larger values from having too much effect.

**Normalization:** Normalization scales the values to a fixed range, usually between 0 and 1.

**Standardization:** Standardization changes the values so that the feature has a mean of 0 and a standard deviation of 1.

A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN? 

**Answer**



Functions such as `np.nanmean()` exist to calculate the mean of data while **ignoring NaN values**. This is useful when the dataset contains missing values.


If `np.mean()` is used directly on data containing `NaN`, the result will be **NaN** because `np.mean()` does not ignore missing `NaN` values.

A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128. 

**Answer**


In the ML convention, `X.shape = (samples, features)`. For a batch of RGB images, the shape extends to `(number of images, height, width, channels)`, where RGB has 3 channels.

For **64 RGB images** of size **128 × 128**

 The exact shape is **`(64, 128, 128, 3)`**.

A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed). 

**Answer**


Reproducibility is important because it helps us get the same results when we repeat an experiment. It makes the results easier to compare and verify during model development.

Fixing a random seed using `np.random.default_rng(seed)` helps produce the same random values each time the experiment is run. This makes the results reproducible and easier to compare and verify.

Section B – Predict the Output


B1. Predict the exact output and/or resulting shape. Justify in one sentence. 

a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)




### predicted  output

```text
(3, 3)

**Justification:**

 NumPy broadcasting combines the shapes `(3,)` and `(3, 1)`, resulting in a shape of `(3, 3)`.

B2. Predict the output and/or shape. 

x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])


### predicted  output

```text
[2, 5]

**Justification:** `:` selects all rows and index `1` selects the second column, so the output is `[2 5]`.

B3. Predict the output and/or shape. 

arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])


### predicted  output

```text
[10, 20]

**Justification:** The condition `arr % 10 == 0` selects the elements that are exactly divisible by 10, so the output is `[10 20]`.

B4. Predict the output and/or shape. 

m = np.array([[1, 2], [3, 4]])
print(m.T @ m)



### predicted  output

```text
[[10, 14]
 [14, 20]]

**Justification:** `m.T` gives the transpose of `m`, and `@` performs matrix multiplication, resulting in a 2 × 2 array.

B5. Predict the output and/or shape. 

data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))


### predicted  output

```text
nan 2.3333333333333335

**Justification:** `np.mean()` returns `nan` because the data contains a NaN value, while `np.nanmean()` ignores the NaN value and calculates the mean of the remaining values.

B6. Predict the output and/or shape. 

x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)


### predicted  output

```text
[0, 1, 1]

**Justification:** `np.where()` returns `1` for values greater than 15 and `0` for values that are not greater than 15.

B7. Predict the output and/or shape. 

a = np.zeros((3, 4))
print(a.ndim, a.size)


### predicted  output

```text
(2, 12)

**Justification:** The array has 2 dimensions and contains 3 × 4 = 12 elements.

B8. Predict the output and/or shape. 

arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])



### predicted  output

```text
[[12, 11, 10,  9]
 [ 8,  7,  6,  5]
 [ 4,  3,  2,  1]]

**Justification:** `[::-1, ::-1]` reverses both the rows and columns of the array.

Section C – Coding / Implementation


C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40).

**Answer**


In [16]:
import numpy as np

scores = np.array([35, 45, 60, 28, 75])

labels = np.where(scores >= 40, 'P', 'F')

print("Scores:", scores)
print("Labels:", labels)

Scores: [35 45 60 28 75]
Labels: ['F' 'P' 'P' 'F' 'P']


Explanation

The given 1D NumPy array contains the exam scores of different students. The np.where() function checks each score against the condition scores >= 40. If the condition is true, the student is given the label P, which means Pass. If the condition is false, the student is given the label F, which means Fail. Therefore, scores below 40 are labelled F, while scores of 40 or above are labelled P.

C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy. 

**Answer**


In [17]:
import numpy as np

def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

x = np.array([10, 20, 30, 40, 50])

result = standardize(x)

print(result)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Explanation

The standardize() function takes a 1D NumPy array as input and calculates its mean and standard deviation using NumPy. It then subtracts the mean from each value and divides the result by the standard deviation. This converts the values into their z-score standardized form, where the values are centered around a mean of 0.

C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape. 

**Answer**


In [18]:
import numpy as np

batch1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

batch2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

combined = np.vstack((batch1, batch2))

print(combined)
print("Resulting shape:", combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Resulting shape: (4, 3)


Explanation

The two arrays represent separate batches and both have 3 features (columns). The np.vstack() function combines them vertically by adding the rows of batch2 below the rows of batch1. Since each batch has 2 rows and 3 columns, the combined array has 4 rows and 3 columns, giving the shape (4, 3).

C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression. 

**Answer**


In [19]:
import numpy as np

X = np.random.default_rng(1).normal(size=(100, 5))

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std

print("Mean:", mean)
print("Standard deviation:", std)
print("Standardized shape:", X_standardized.shape)

Mean: [-0.02552467  0.0098774  -0.12023339 -0.10931636  0.06650542]
Standard deviation: [0.91019581 0.81743994 0.88525617 1.05773411 0.86200884]
Standardized shape: (100, 5)


Explanation

The matrix X has 100 samples and 5 features. Using axis=0 calculates the mean and standard deviation separately for each of the 5 columns. The expression (X - mean) / std uses NumPy broadcasting to standardize all 100 rows at once without using a loop.

C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true. 

**Answer**


In [21]:
import numpy as np

X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

w = np.array([2, 3])
b = 1

y_true = np.array([8, 20, 28])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [ 9 19 29]
MSE: 1.0


Explanation

The expression X @ w + b calculates the predicted values using matrix multiplication and the bias. The predicted values are then compared with y_true. The MSE is calculated by taking the average of the squared differences between the actual and predicted values. NumPy performs these calculations directly without using a loop.

C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed. 

**Answer**


In [22]:
import numpy as np

seed = 42

rng1 = np.random.default_rng(seed)
data1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(seed)
data2 = rng2.normal(size=(10, 3))

print("Shape:", data1.shape)
print("Identical results:", np.array_equal(data1, data2))

Shape: (10, 3)
Identical results: True


Explanation

The code creates 10 samples and 3 features from a normal distribution using np.random.default_rng(). The seed 42 makes the random values reproducible. Two generators are created with the same seed, so both produce identical arrays. np.array_equal() confirms that the two results are exactly the same.

C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization. 

**Answer**


In [23]:
import numpy as np

image = np.array([[0, 50, 100],
                  [150, 200, 255]])

min_value = np.min(image)
max_value = np.max(image)

normalized_image = (image - min_value) / (max_value - min_value)

print("Original image:")
print(image)

print("Normalized image:")
print(normalized_image)

Original image:
[[  0  50 100]
 [150 200 255]]
Normalized image:
[[0.         0.19607843 0.39215686]
 [0.58823529 0.78431373 1.        ]]


Explanation

The grayscale image contains pixel values from 0 to 255. The min-max formula (image - min) / (max - min) converts these values to the range 0 to 1. The minimum pixel value becomes 0 and the maximum becomes 1.

C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why. 

**Answer**


In [24]:
import numpy as np

images = np.random.default_rng(1).integers(0, 256, size=(4, 28, 28, 3))

average_pixel = np.mean(images, axis=(1, 2, 3))

print("Average pixel value of each image:")
print(average_pixel)

Average pixel value of each image:
[129.87797619 126.35119048 126.14668367 129.85204082]


Explanation

The images have the shape (4, 28, 28, 3), where 4 represents the number of images. We use axis=(1, 2, 3) to average across the height, width, and RGB channels while keeping each image separate. Therefore, the result contains 4 average pixel values, one for each image.

Section D – Applied / Scenario-Based Problems


D1. Data Preprocessing Pipeline 

You are given a raw 1D or 2D NumPy array containing NaN values.

Describe, step by step, the NumPy operations you would apply to :


(a) detect missing values

**Answer**

In [6]:
import numpy as np

data = np.array([10, 20, np.nan, 40, 50])

missing = np.isnan(data)

print("Missing values:")
print(missing)

Missing values:
[False False  True False False]


Explanation

First, np.isnan(data) is used to detect missing values in the array. It checks each element and returns True if the value is NaN, otherwise it returns False. This helps us identify the position of missing data.

(b) handle them appropriately and justify your strategy, and

**Answer**

In [10]:
import numpy as np

data = np.array([10, 20, np.nan, 40, 50])

mean_value = np.nanmean(data)
clean_data = np.where(np.isnan(data), mean_value, data)

print("\n Mean used to replace NaN:")
print(mean_value)

print("Clean data:")
print(clean_data)


 Mean used to replace NaN:
30.0
Clean data:
[10. 20. 30. 40. 50.]


Explanation

Next, the missing value needs to be handled before using the data for a model. Here, np.nanmean(data) calculates the mean while ignoring the NaN value. The np.where() function then replaces the missing value with this mean. This strategy keeps the same number of data values without deleting any sample.

(c) normalize or standardize the clean data before it is fed to a model.

**Answer**

In [11]:
mean = np.mean(clean_data)
std = np.std(clean_data)

standardized_data = (clean_data - mean) / std

print("\n(c) Standardized data:")
print(standardized_data)


(c) Standardized data:
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Explanation

After handling the missing value, the cleaned data is standardized. We calculate its mean and standard deviation using np.mean() and np.std(). The formula (data - mean) / std converts the values to a common scale, with the resulting data centered around 0.

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.


In [12]:
import numpy as np

# Sample array containing a NaN value
data = np.array([10, 20, np.nan, 40, 50])

# (a) Detect missing values
missing = np.isnan(data)

print("(a) Missing values:")
print(missing)

# (b) Handle missing value using the mean
mean_value = np.nanmean(data)
clean_data = np.where(np.isnan(data), mean_value, data)

print("\n(b) Clean data:")
print(clean_data)

# (c) Standardize the clean data
mean = np.mean(clean_data)
std = np.std(clean_data)

standardized_data = (clean_data - mean) / std

print("\n(c) Standardized data:")
print(standardized_data)

(a) Missing values:
[False False  True False False]

(b) Clean data:
[10. 20. 30. 40. 50.]

(c) Standardized data:
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Final Result

The final data is now clean, contains no NaN values, and is standardized to a common scale. This cleaned and standardized data can now be provided as input to a machine-learning model.

D2. Image Batch Understanding 

1 Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images

**Answer**

In [14]:
import numpy as np

# Single RGB image
image = np.zeros((64, 64, 3))

# Batch of 16 RGB images
images = np.zeros((16, 64, 64, 3))

print("Single image shape:", image.shape)
print("Batch shape:", images.shape)

Single image shape: (64, 64, 3)
Batch shape: (16, 64, 64, 3)


**Explanation:** 

A single RGB image has the shape (64, 64, 3). The first two values represent the image height and width, while 3 represents the RGB color channels. A batch of 16 images adds one extra dimension for the number of images, so its shape is (16, 64, 64, 3).

2 Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

**Answer**

In [15]:
import numpy as np

rng = np.random.default_rng(42)

images = rng.integers(0, 256, size=(16, 64, 64, 3))

print("Batch shape:", images.shape)

Batch shape: (16, 64, 64, 3)


Explanation

The code creates 16 RGB images, each with a height and width of 64 × 64. The value 3 represents the three RGB channels. rng.integers(0, 256) generates random pixel values from 0 to 255. Therefore, the complete batch has the shape (16, 64, 64, 3).

3  Compute the average image of the batch, meaning the element-wise mean across all 16 images.

**Answers**

In [16]:
average_image = np.mean(images, axis=0)

print("Average image shape:", average_image.shape)

Average image shape: (64, 64, 3)


Explanation

np.mean() calculates the mean pixel value across the 16 images. We use axis=0 because the first dimension represents the 16 images. The height, width, and RGB channel dimensions are kept unchanged. Therefore, the average of the batch is one RGB image with shape (64, 64, 3).

4 State the shape of your result and explain why.

**Answer**

In [19]:
print("Average image shape:", average_image.shape)

Average image shape: (64, 64, 3)


Explanation

The average image has shape (64, 64, 3). The 16 images were averaged using axis=0, so the batch dimension is removed. The height, width, and 3 RGB channels remain unchanged.

D3. Debug the Model Code 
The following code contains more than one bug:

X = np.array([[1, 2],

              [2, 3],

              [3, 4]])  # shape (3, 2)

w = np.array([0.5, 1.0, 0.2])  # intended weight vector

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean(y_true - y_pred ** 2)

Identify every bug. Explain, in terms of shapes and operator precedence, why each is a problem, and rewrite the corrected code.

**Answer**

In [20]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


Explanation

X has shape (3, 2), so w must have shape (2,) for the matrix multiplication X @ w to work. The bias b is then added to each predicted value using broadcasting. The original MSE expression also had an operator-precedence problem because the subtraction was not enclosed in parentheses. The corrected expression (y_true - y_pred) ** 2 calculates the squared errors before taking their mean.

Section E – Bonus / Challenge


E1. Per-Column Min–Max Normalization 

Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.

**Answer**



In [21]:
import numpy as np

X = np.array([[10, 100, 1000],
              [20, 200, 2000],
              [30, 300, 3000],
              [40, 400, 4000]])

# Find minimum and maximum of each column
col_min = np.min(X, axis=0)
col_max = np.max(X, axis=0)

# Per-column Min-Max normalization
X_normalized = (X - col_min) / (col_max - col_min)

print("Original matrix:")
print(X)

print("\nColumn-wise minimum:")
print(col_min)

print("\nColumn-wise maximum:")
print(col_max)

print("\nNormalized matrix:")
print(X_normalized)

Original matrix:
[[  10  100 1000]
 [  20  200 2000]
 [  30  300 3000]
 [  40  400 4000]]

Column-wise minimum:
[  10  100 1000]

Column-wise maximum:
[  40  400 4000]

Normalized matrix:
[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]


Explanation

The matrix contains multiple features as columns, so np.min(X, axis=0) and np.max(X, axis=0) find the minimum and maximum separately for each column. The formula (X - col_min) / (col_max - col_min) is then applied using NumPy broadcasting, so there is no need for explicit loops. Each column is independently scaled to the range 0 to 1. This is different from using one global minimum and maximum for the entire matrix.

E2. Three-Level Score Classification 


Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:


Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).


Hint: You may need to nest or combine np.where() calls.

**Answer**


In [22]:
import numpy as np

scores = np.array([25, 40, 55, 70, 75, 90])

result = np.where(scores < 40, "Fail",
                  np.where(scores <= 70, "Average", "Excellent"))

print("Scores:", scores)
print("Classification:", result)

Scores: [25 40 55 70 75 90]
Classification: ['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']


Explanation

The first np.where() checks whether each score is less than 40; if true, it assigns "Fail". For scores that are not below 40, the second np.where() checks whether the score is less than or equal to 70 and assigns "Average". Scores greater than 70 are classified as "Excellent". The entire classification is performed using a single vectorized expression without any if/else statements or explicit loops.