<div align="center">

# Pandas Assessment



**Submitted By:** Chippada Hemalatha

**Batch:**  Batch 3




</div>

**Contents:** Section A – Output Prediction | Section B – Code Correction | Section C – Edge Cases | Section D – Scenario-Based Questions


In [1]:
import numpy as np
import pandas as pd
print("numpy version:", np.__version__)
print("pandas version:", pd.__version__)

numpy version: 2.5.3
pandas version: 3.0.5


# SECTION A – OUTPUT PREDICTION

 # Q1.  Array operations and vectorization


import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)

1)Predict the output of both statements.

2)Identify one similarity and one difference between the two data structures.



**Answer:**



### 1. Predict the output of both statements.

The output of `arr * 2` is:

```text
[20 40 60]
```

The output of `s * 2` is:

```text
0    20
1    40
2    60
dtype: int64
```

### 2. Identify one similarity and one difference between the two data structures.

**Similarity:** Both NumPy arrays and Pandas Series support element-wise operations such as multiplication by 2.

**Difference:** A NumPy array mainly stores values, whereas a Pandas Series stores values along with an index.

### Explanation

Both `arr` and `s` contain the values 10, 20, and 30. When multiplied by 2, each value is multiplied individually. The Pandas Series also displays an index (0, 1, 2) along with the values.


# Code executed output

In [2]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)

[20 40 60]
0    20
1    40
2    60
dtype: int64


# Q2. Boolean Filtering


import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks’]])

1)Predict the rows displayed.

2)How many rows and columns will the resulting DataFrame contain?


**Answer:**


### 1. Predict the rows displayed.

The rows displayed are:

| Student | Marks |
| ------- | ----: |
| B       |    80 |
| C       |    65 |
| D       |    90 |

Only students with marks **greater than or equal to 65** are selected.

### 2. How many rows and columns will the resulting DataFrame contain?

The resulting DataFrame contains **3 rows and 2 columns**.

**Shape:** `(3, 2)`


### Explanation

The condition `df['Marks'] >= 65` checks which students have marks greater than or equal to 65. Students B, C, and D satisfy this condition, so their rows are selected. The resulting DataFrame contains only the `Student` and `Marks` columns, giving **3 rows and 2 columns**.


# Code executed output

In [3]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])


  Student  Marks
1       B     80
2       C     65
3       D     90


# Q3.  Descriptive statistics


import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())

1)Predict all three outputs.

2)Explain how the median differs from the mean.


**Answer:**


### 1. Predict all three outputs.

The output of `mean()` is:

```text
30.0
```

The output of `max()` is:

```text
50
```

The output of `median()` is:

```text
30.0
```

### 2. Explain how the median differs from the mean.

**Mean:** The mean is calculated by adding all the values and dividing the sum by the number of values.

**Median:** The median is the middle value when the data is arranged in sorted order.

### Explanation

For the marks `[10, 20, 30, 40, 50]`, the mean is 30 and the median is also 30. The median is less affected by extreme values than the mean.


# Code executed output

In [4]:
import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())


30.0
50
30.0


# Q4.  Group-wise Analysis


import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())


1)Predict the output.

2)Explain how groupby() calculates the department-wise average.


**Answer:**


### 1. Predict the output.

```text
Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64
```

### 2. Explain how `groupby()` calculates the department-wise average.

The `groupby('Department')` operation groups the rows based on the department. Then `['Salary'].mean()` calculates the average salary for each department.

For **IT**:

`(40000 + 60000) / 2 = 50000`

For **HR**:

`(30000 + 50000) / 2 = 40000`

### Explanation

The DataFrame contains two employees in each department. Pandas groups the employees by department and calculates the mean salary separately for each group.


# Code executed output

In [5]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())


Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


# Q5.   Pandas Correlation - Positive


import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks’]))

1)Predict the correlation coefficient.

2)Interpret the direction and strength of the relationship

**Answer:**



### 1. Predict the correlation coefficient.

The correlation coefficient is:

```text
1.0
```

### 2. Interpret the direction and strength of the relationship.

The correlation is **positive and perfect**. This means that as the number of **Hours** increases, **Marks** also increase in a perfectly consistent relationship.

### Explanation

The `corr()` function calculates the correlation between the `Hours` and `Marks` columns. Since the values increase proportionally (`1 → 20`, `2 → 40`, `3 → 60`, `4 → 80`), the correlation coefficient is **1.0**.


# Code executed output

In [6]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))



1.0


# Q6.  Pandas Correlation - Negative


import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))

1)Predict the correlation coefficient.

2)Explain what the sign of the coefficient indicates about the relationship.



**Answer:**



### 1. Predict the correlation coefficient.

The correlation coefficient is:

```text
-1.0
```

### 2. Explain what the sign of the coefficient indicates about the relationship.

The negative sign indicates a **negative relationship** between Price and Demand. As the **Price increases, Demand decreases**.

### Explanation

The `corr()` function calculates the correlation between the `Price` and `Demand` columns. Since Price increases while Demand decreases in a perfectly consistent way, the correlation coefficient is **-1.0**, indicating a perfect negative relationship.


# Code executed output


In [7]:
import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))


-1.0


# SECTION B – CODE CORRECTION


## Q1. JSON and CSV

```python
import pandas as pd

df = pd.read_csv("students.csv", header=None)
print(df)
```

A CSV file contains a header row, but the following code incorrectly reads the first student's record as column names. Correct the code.


**Answer:**




**Issue:** `header=None` tells Pandas that the CSV file does not contain a header row. Therefore, the first row is treated as data instead of column names.

**Corrected Code:**

```python
import pandas as pd

df = pd.read_csv("students.csv", header=0)
print(df)
```

**Explanation:** `header=0` tells Pandas to use the first row of the CSV file as the column names.


# Q2. Data Analysis

import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary').head(5))                              

The objective is to display the five highest salaries from a DataFrame. Correct the code.


**Answer:**




**Issue:** `sort_values('Salary')` sorts the salaries in ascending order, so `head(5)` selects the five lowest salaries.

**Corrected Code:**

```python
print(df.sort_values('Salary', ascending=False).head(5))
```

**Expected Output:**

```text
  Employee  Salary
5         F   70000
3         D   60000
1         B   50000
4         E   45000
0         A   30000
```

**Explanation:** `ascending=False` sorts the salaries from highest to lowest, and `head(5)` selects the five highest salaries.


# Q3. Cleaning Data          


import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'].fillna(df['Marks'].mean())
print(df)    

A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code.



**Answer:**




**Issue:** `fillna()` returns a new Series by default, but the result is not assigned back to the `Marks` column.

**Corrected Code:**

```python
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)
```

**Expected Output:**

```text
   Marks
0   70.0
1   80.0
2   90.0
```

**Explanation:** The mean of the available marks is `(70 + 90) / 2 = 80`. The missing value is replaced with `80`.


# Q4. Correlation


import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df.corr('Hours', 'Marks’))

The objective is to calculate the correlation between Hours and Marks. Correct the code.



### Answer

**Issue:** `df.corr('Hours', 'Marks')` is incorrect because `corr()` does not take column names as positional arguments.

**Corrected Code:**

```python
print(df['Hours'].corr(df['Marks']))
```

**Expected Output:**

```text
1.0
```

**Explanation:** The `corr()` method is used between the `Hours` and `Marks` Series to calculate their correlation. Since both values increase proportionally, the correlation is **1.0**.


# SECTION C – EDGE CASES


## Q1. Two NumPy arrays have shapes (3, 1) and (1, 3). Predict the shape of their element-wise sum and explain how broadcasting works. Why might the result differ from adding two one-dimensional arrays?

```python
import numpy as np

a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])

result = a + b

print(result)
print(result.shape)
```

1)Predict the output of the given code.

2)Identify the shapes of arrays a and b before addition.

3)Explain how NumPy broadcasting enables the addition of these arrays.

4)What would happen if b were replaced with np.array([1, 2])? Explain the reason.

**Answer:**



### 1. Predict the output of the given code

```text
[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)
```

### 2. Shapes of arrays before addition

* Shape of `a` = `(3, 1)`
* Shape of `b` = `(1, 3)`

### 3. How broadcasting enables the addition

NumPy broadcasting allows arrays with compatible shapes to be used in element-wise operations without manually changing their sizes.

Here, `a` has shape `(3, 1)` and `b` has shape `(1, 3)`. NumPy broadcasts them to a common shape of `(3, 3)` and performs element-wise addition.

For example:

```text
[10] + [1 2 3] = [11 12 13]
[20] + [1 2 3] = [21 22 23]
[30] + [1 2 3] = [31 32 33]
```

### 4. What happens if `b = np.array([1, 2])`?

The shapes become:

* `a` = `(3, 1)`
* `b` = `(2,)`

These shapes **are compatible for broadcasting**. NumPy treats `b` as having shape `(1, 2)` and broadcasts both arrays to `(3, 2)`.

The result will be:

```text
[[11 12]
 [21 22]
 [31 32]]
```

The result shape is:

```text
(3, 2)
```

This differs from adding two one-dimensional arrays because a 2D array with shape `(3, 1)` can broadcast across the columns, while two 1D arrays are aligned element-by-element and normally need compatible lengths.


# Code executed output

In [8]:
import numpy as np

a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])

print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

result = a + b

print(result)
print(result.shape)

Shape of a: (3, 1)
Shape of b: (1, 3)
[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


### Explanation

Broadcasting means NumPy automatically adjusts the shapes of compatible arrays so that element-wise operations can be performed.

Here:

- `a` has shape `(3, 1)` → 3 rows and 1 column.
- `b` has shape `(1, 3)` → 1 row and 3 columns.

NumPy broadcasts both arrays to a common shape of `(3, 3)`:

```text
a:              b:

[10]            [1 2 3]
[20]            [1 2 3]
[30]            [1 2 3]

## Q2. A CSV file contains commas inside quoted text fields, missing values, and dates in different formats. Explain how incorrect parsing can affect the resulting DataFrame and identify suitable read options or preprocessing steps.

Given dataset: students.csv
```
ID,Name,Date,Marks
101,"Asha, R",2026-09-01,80
102,Ravi,01/09/2026,
103,Neha,2026-09-03,NA
```

Given code:
```python
import pandas as pd

df = pd.read_csv("students.csv")

print(df)
print(df.dtypes)
```

1)Predict how the quoted comma in "Asha, R" will be handled when the CSV file is read.

2)Identify the potential issues with the Date and Marks columns.

3)Rewrite the code to handle missing marks and convert the date column into a suitable date-time format.

4)Explain why the value "NA" should be investigated before deciding whether it represents a missing value.

**Answer:**


### 1. Handling the quoted comma

The value `"Asha, R"` is enclosed in double quotes, so Pandas correctly treats the comma inside the quotes as part of the `Name` field rather than as a column separator.

Therefore, the first row will be read correctly as:

| ID | Name | Date | Marks |
|---|---|---|---|
| 101 | Asha, R | 2026-09-01 | 80 |

### 2. Potential issues with Date and Marks columns

- The `Date` column contains dates in different formats, such as `2026-09-01` and `01/09/2026`. These should be converted into a consistent date-time format.
- The `Marks` column contains a missing value for Ravi and the value `NA` for Neha. These should be handled carefully before performing numerical analysis.

### 3. Code to handle missing marks and convert the Date column

```python
import pandas as pd

df = pd.read_csv("students.csv", na_values=["NA", ""])

df["Date"] = pd.to_datetime(df["Date"], errors="coerce", dayfirst=True)

df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

print(df)
print(df.dtypes)

### 4. Why should `"NA"` be investigated?

The value `"NA"` may mean **Not Available**, **Not Applicable**, **Absent**, or it may simply be a missing value.

Therefore, it should be investigated before automatically treating it as missing data, because different meanings can affect the analysis and conclusions.

## Q3. A salary column contains the values 25000, 30000, 35000, and 10000000. Explain how the extreme value affects the mean compared with the median. Identify which statistic may better represent a typical employee's salary and justify your choice.

Given code:
```python
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())
```

1)Predict the mean and median salary.

2)Identify the effect of the extreme salary on the mean.

3)Which statistic may better represent a typical employee's salary in this dataset? Justify your answer.

4)Write code to identify the employee record with the highest salary and explain why the record should be investigated before removing it

**Answer:**


### 1. Predict the mean and median salary

The mean salary is **2,522,500**.

The median salary is **32,500**.

### 2. Effect of the extreme salary on the mean

The salary `10,000,000` is an extreme value compared with the other salaries.

It greatly increases the mean because the mean is calculated using every value in the dataset. Therefore, the mean becomes much higher than the salaries of most employees.

### 3. Which statistic better represents a typical employee's salary?

The **median** may better represent a typical employee's salary in this dataset.

The median is **32,500**, which is close to the salaries of the first three employees. It is less affected by the extreme value than the mean.

### 4. Identify the employee with the highest salary

```python
highest_salary = df.loc[df["Salary"].idxmax()]
print(highest_salary)

In [9]:

highest_salary = df.loc[df["Salary"].idxmax()]
print(highest_salary)

KeyError: 'Salary'

# Code executed output

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())


Mean: 2522500.0
Median: 32500.0


### Explanation

The **mean** is calculated by adding all salaries and dividing by the number of employees. Because `10,000,000` is extremely large compared with the other salaries, it greatly increases the mean to `2,522,500`.

The **median** is the middle value after arranging the salaries in ascending order. The salaries are:

`25000, 30000, 35000, 10000000`

The middle two values are `30000` and `35000`, so the median is `32,500`.

Therefore, the **median** better represents a typical employee's salary because it is less affected by the extreme value.

The following code identifies the employee with the highest salary:

```python
highest_salary = df.loc[df["Salary"].idxmax()]
print(highest_salary)

# SECTION D – SCENARIO-BASED QUESTIONS
*Read each business or real-world scenario and develop a Pandas-based solution. Justify the methods, operations, or file formats selected.*

## Q1. A student assessment dataset contains missing marks, duplicate student records, inconsistent department names such as IT, it, and I.T., and marks stored as text. Develop a cleaning sequence to standardize the data, handle missing values, remove duplicates, and convert marks into a suitable numeric type. State one risk of deleting missing values without investigating why they are missing.

Dataset: student_assessment_dirty.csv

| Student_ID | Student_Name | Department | Assessment | Marks |
| --- | --- | --- | --- | --- |
| S101 | Asha | IT | Python | 85 |
| S102 | Ravi | it | Python | 78 |
| S103 | Neha | I.T. | Python | 92 |
| S104 | Karan | HR | Python |  |
| S105 | Meera | HR | Python | Absent |
| S106 | Arjun | Finance | Python | 0 |
| S107 | Priya | finance | Python | 67 |
| S108 | Rahul | IT | Python | 75 |
| S102 | Ravi | it | Python | 78 |
| S109 | Sneha | I.T. | Python | NA |
| S110 | Varun | HR | Python | 88 marks |
| S111 | Diya | Finance | Python | 91 |
| S112 | Aman | IT | Python |  |
| S113 | Nisha | HR | Python | 64 |
| S114 | Kabir | Finance | Python | 105 |

Using Pandas, perform the following cleaning operations in sequence:

1. Load the CSV file and inspect the dataset using head(), info(), and isnull().sum().
2. Standardize department names so that IT, it, and I.T. are represented consistently. Apply the same approach to Finance.
3. Identify and remove exact duplicate student assessment records.
4. Convert the Marks column into a numeric format, handling "88 marks", "Absent", "NA", and blank entries appropriately.
5. Investigate missing marks and distinguish absent students from students whose marks have not been entered. State one risk of deleting missing values without investigating why they are missing.
6. Identify marks outside the valid range of 0–100 and decide how they should be handled.
7. Display the cleaned DataFrame and report the number of records removed, missing marks remaining, and invalid marks identified.

**Answer:**

**Setup:** the dataset from the question is saved as `student_assessment_dirty.csv` so that it can be loaded.

In [ ]:
csv_text = '''Student_ID,Student_Name,Department,Assessment,Marks
S101,Asha,IT,Python,85
S102,Ravi,it,Python,78
S103,Neha,I.T.,Python,92
S104,Karan,HR,Python,
S105,Meera,HR,Python,Absent
S106,Arjun,Finance,Python,0
S107,Priya,finance,Python,67
S108,Rahul,IT,Python,75
S102,Ravi,it,Python,78
S109,Sneha,I.T.,Python,NA
S110,Varun,HR,Python,88 marks
S111,Diya,Finance,Python,91
S112,Aman,IT,Python,
S113,Nisha,HR,Python,64
S114,Kabir,Finance,Python,105
'''
with open("student_assessment_dirty.csv", "w") as f:
    f.write(csv_text)
print("student_assessment_dirty.csv created")

student_assessment_dirty.csv created


### Step 1 – Load the CSV file and inspect the dataset
`keep_default_na=False` is used on purpose so that the text `NA` is **kept as text** and can be investigated later (instead of silently becoming `NaN`). Only truly blank cells are treated as missing.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("student_assessment_dirty.csv",
                 keep_default_na=False, na_values=[""])
rows_before = len(df)

print(df.head())
print()
df.info()
print()
print(df.isnull().sum())

  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str  
 1   Student_Name  15 non-null     str  
 2   Department    15 non-null     str  
 3   Assessment    15 non-null     str  
 4   Marks         13 non-null     str  
dtypes: str(5)
memory usage: 732.0 bytes

Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           2
dtype: int64


**Expected Output** (dtype text shows as `object` in older Pandas and `str` in Pandas 3.x)
```
  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent

RangeIndex: 15 entries, 0 to 14 ... Marks: 13 non-null (text)

Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           2
dtype: int64
```
**Explanation:** `head()` previews the rows, `info()` shows that Marks is stored as text (not numeric), and `isnull().sum()` shows only 2 real blanks – the values `NA` and `Absent` are text, so they are not counted yet.

### Step 2 – Standardize department names

In [ ]:
df["Department"] = (df["Department"].str.strip()
                                    .str.upper()
                                    .str.replace(".", "", regex=False))
df["Department"] = df["Department"].replace({"FINANCE": "Finance"})

print(df["Department"].value_counts())

Department
IT         7
HR         4
Finance    4
Name: count, dtype: int64


**Expected Output**
```
Department
IT         7
HR         4
Finance    4
Name: count, dtype: int64
```
**Explanation:** `IT`, `it` and `I.T.` all become `IT` (uppercase and dots removed), and `finance` / `Finance` both become `Finance`. This count still includes the duplicate row, which is removed in the next step. Standardizing *before* removing duplicates makes sure rows that differ only in spelling are matched correctly.

### Step 3 – Identify and remove exact duplicate records

In [ ]:
print("Duplicate rows found:", df.duplicated().sum())
print(df[df.duplicated(keep=False)])

df = df.drop_duplicates()
records_removed = rows_before - len(df)

print("Records removed:", records_removed)
print("Rows remaining:", len(df))

Duplicate rows found: 1
  Student_ID Student_Name Department Assessment Marks
1       S102         Ravi         IT     Python    78
8       S102         Ravi         IT     Python    78
Records removed: 1
Rows remaining: 14


**Expected Output**
```
Duplicate rows found: 1
   Student_ID Student_Name Department Assessment Marks
1        S102         Ravi         IT     Python    78
8        S102         Ravi         IT     Python    78
Records removed: 1
Rows remaining: 14
```
**Explanation:** `duplicated()` finds identical rows and `drop_duplicates()` keeps the first copy. The repeated S102 (Ravi) record is removed.

### Step 4 – Convert Marks to a numeric format
The original text is kept in `Marks_Raw` so that missing values can be investigated in Step 5.

In [ ]:
df["Marks_Raw"] = df["Marks"]

df["Marks"] = pd.to_numeric(
    df["Marks"].str.extract(r"(\d+\.?\d*)")[0],
    errors="coerce"
)

print(df[["Student_ID", "Student_Name", "Marks_Raw", "Marks"]])
print()
print(df["Marks"].dtype)

   Student_ID Student_Name Marks_Raw  Marks
0        S101         Asha        85   85.0
1        S102         Ravi        78   78.0
2        S103         Neha        92   92.0
3        S104        Karan       NaN    NaN
4        S105        Meera    Absent    NaN
5        S106        Arjun         0    0.0
6        S107        Priya        67   67.0
7        S108        Rahul        75   75.0
9        S109        Sneha        NA    NaN
10       S110        Varun  88 marks   88.0
11       S111         Diya        91   91.0
12       S112         Aman       NaN    NaN
13       S113        Nisha        64   64.0
14       S114        Kabir       105  105.0

float64


**Expected Output**
```
   Student_ID Student_Name Marks_Raw  Marks
0        S101         Asha        85   85.0
1        S102         Ravi        78   78.0
2        S103         Neha        92   92.0
3        S104        Karan       NaN    NaN
4        S105        Meera    Absent    NaN
5        S106        Arjun         0    0.0
6        S107        Priya        67   67.0
7        S108        Rahul        75   75.0
9        S109        Sneha        NA    NaN
10       S110        Varun  88 marks   88.0
11       S111         Diya        91   91.0
12       S112         Aman       NaN    NaN
13       S113        Nisha        64   64.0
14       S114        Kabir       105  105.0

float64
```
**Explanation:** the regular expression pulls the number out of `88 marks`, and `pd.to_numeric(..., errors="coerce")` turns `Absent`, `NA` and blanks into `NaN`. The column becomes `float64` (a float type is needed because integers cannot store `NaN`).

### Step 5 – Investigate missing marks (absent vs. not entered)

In [ ]:
df["Marks_Status"] = "Entered"
df.loc[df["Marks_Raw"].isna(), "Marks_Status"] = "Not entered (blank)"
df.loc[df["Marks_Raw"] == "NA", "Marks_Status"] = "NA - check source"
df.loc[df["Marks_Raw"].str.strip().str.lower() == "absent", "Marks_Status"] = "Absent"

missing = df[df["Marks"].isna()]
print(missing[["Student_ID", "Student_Name", "Marks_Raw", "Marks_Status"]])

   Student_ID Student_Name Marks_Raw         Marks_Status
3        S104        Karan       NaN  Not entered (blank)
4        S105        Meera    Absent               Absent
9        S109        Sneha        NA    NA - check source
12       S112         Aman       NaN  Not entered (blank)


**Expected Output**
```
   Student_ID Student_Name Marks_Raw         Marks_Status
3        S104        Karan       NaN  Not entered (blank)
4        S105        Meera    Absent               Absent
9        S109        Sneha        NA    NA - check source
12       S112         Aman       NaN  Not entered (blank)
```
**Explanation:**
- **Meera** is genuinely **absent** – a real outcome, not a data problem.
- **Karan and Aman** have **blank** marks, which were most likely never entered and should be collected/filled from the source.
- **Sneha** has `NA`, which is unclear (not applicable? not entered?) and must be checked with the source.

**One risk of deleting missing values without investigating:** you may delete students who were genuinely absent or whose marks were simply not entered. This biases the results (for example, class averages look higher than they really are) and hides a data-entry problem that should have been fixed.

### Step 6 – Identify marks outside the valid range 0–100

In [ ]:
df["Invalid_Marks"] = (df["Marks"] < 0) | (df["Marks"] > 100)

print(df[df["Invalid_Marks"]][["Student_ID", "Student_Name", "Marks"]])

   Student_ID Student_Name  Marks
14       S114        Kabir  105.0


**Expected Output**
```
   Student_ID Student_Name  Marks
14       S114        Kabir  105.0
```
**How it should be handled:** Kabir's 105 is impossible on a 0–100 scale, so the row is **flagged, not deleted**. The value should be verified with the source (it may be a typing mistake such as 95 or 10.5). If it cannot be verified, it can be set to `NaN`. Arjun's mark of 0 is **valid** (it is inside 0–100) but is worth confirming that it is not a placeholder for a missing mark.

### Step 7 – Cleaned DataFrame and final report

In [ ]:
cleaned_df = df.drop(columns="Marks_Raw")
print(cleaned_df.to_string())
print()
print("Records removed         :", records_removed)
print("Missing marks remaining :", df["Marks"].isna().sum())
print("Invalid marks identified:", df["Invalid_Marks"].sum())

   Student_ID Student_Name Department Assessment  Marks         Marks_Status  Invalid_Marks
0        S101         Asha         IT     Python   85.0              Entered          False
1        S102         Ravi         IT     Python   78.0              Entered          False
2        S103         Neha         IT     Python   92.0              Entered          False
3        S104        Karan         HR     Python    NaN  Not entered (blank)          False
4        S105        Meera         HR     Python    NaN               Absent          False
5        S106        Arjun    Finance     Python    0.0              Entered          False
6        S107        Priya    Finance     Python   67.0              Entered          False
7        S108        Rahul         IT     Python   75.0              Entered          False
9        S109        Sneha         IT     Python    NaN    NA - check source          False
10       S110        Varun         HR     Python   88.0              Entered    

**Expected Output**
```
   Student_ID Student_Name Department Assessment  Marks         Marks_Status  Invalid_Marks
0        S101         Asha         IT     Python   85.0              Entered          False
1        S102         Ravi         IT     Python   78.0              Entered          False
2        S103         Neha         IT     Python   92.0              Entered          False
3        S104        Karan         HR     Python    NaN  Not entered (blank)          False
4        S105        Meera         HR     Python    NaN               Absent          False
5        S106        Arjun    Finance     Python    0.0              Entered          False
6        S107        Priya    Finance     Python   67.0              Entered          False
7        S108        Rahul         IT     Python   75.0              Entered          False
9        S109        Sneha         IT     Python    NaN    NA - check source          False
10       S110        Varun         HR     Python   88.0              Entered          False
11       S111         Diya    Finance     Python   91.0              Entered          False
12       S112         Aman         IT     Python    NaN  Not entered (blank)          False
13       S113        Nisha         HR     Python   64.0              Entered          False
14       S114        Kabir    Finance     Python  105.0              Entered           True

Records removed         : 1
Missing marks remaining : 4
Invalid marks identified: 1
```

| Report item | Count | Details |
|---|---|---|
| Records removed | **1** | Duplicate S102 (Ravi) |
| Missing marks remaining | **4** | Karan (blank), Meera (Absent), Sneha (NA), Aman (blank) |
| Invalid marks identified | **1** | Kabir (105 – outside 0–100) |

**Explanation:** the dataset went from 15 rows to 14. Unresolved cases are **flagged and kept**, not deleted, so nothing is lost before the reasons are investigated. (Index 8 is missing because that was the removed duplicate; `cleaned_df.reset_index(drop=True)` would renumber the rows.) If Kabir's 105 is later set to `NaN` after checking, the missing count would become 5.